let text_src =[
    "Chưa gặp được em trời chưa bao giờ sáng, vì em là mặt trời của anh",
    "Nụ cười em đẹp lắm, cười nhìu nhìu cho anh coi nheee",
    "Mong rằng embe của anh sẽ luôn hạnh phúc",
    "Công chúa của anh oiiii, anh yêuuu em",
    "Anh hứa mỗi ngày sẽ iu em nhìu hơnn",
    "Xin lỗi vì những lần anh làm em buồn:< anh z hoi chứ iu em nhìu nhắm",
    "Yeuu lắm aa, nên là hong có được bùn nhe cục dàng",
    "Hôm nay trời đẹp thật, đẹp nhất khi anh có em",
    "Hehe vậy đã hơn 1 năm roii kể từ khi anh yêuu em",
    "Thương em nhắm",
    "Mong rằng những ngày tháng yêu anh sẽ là những kỉ niệm đáng nhớ của em",
    "Cuộc sống đôi khi sẽ khó khăn, nhưng hong sao đâu, dù em có quyết định thế nào thì anh vẫn ủng hộ em màa",
    "Anh chỉ muốn nói với em làaaa anh yêuuuuu em",
    "Chào công chúa nhỏ đáng yêuu",
    "Anh yêu em",
    "Em là công chúa nhỏ của anh",
    "Xin chào, người dễ thương nhất thế giới",
    "Trái tym anh là nhà và em là chủ nhân 😘",
    "Anh không cần thế giới, chỉ cần có em trong đời",
    "Không yêu em thì yêu ai😉",
    "Cảm ơn em vì đã yêu anh",
    "Em là lý do khiến mỗi ngày của anh đều có ý nghĩa",
    "Anh không cần đèn để soi sáng, vì em là ánh sáng đời anh",
    "Chào mặt trời nhỏ của tớ",
    "Nước có cá, bầu trời thì có chim, còn anh đã có em",
    "Cả bầu trời không bằng một nụ cười của em",
    "Vũ trụ có hàng tỉ vì sao, nhưng trái tim anh chỉ quay quanh một quỹ đạo – em",
    "Thời gian cũng có thể giãn nở theo thuyết tương đối, nhưng tình yêu anh dành cho em không đổi",
    "Em thích nắng, thích hoa, còn anh thì thích em ❤",
    "Nếu anh có một điều ước, anh ước có em mãi mãi",
    "Mỗi sáng tỉnh giấc, điều tuyệt vời nhất là được nói lời yêu với em",
    "Embe ăn dì chua đooo, đừng mê coi web của anh mà quên ăn nhee",
    "Em là embe của anhh",
    "Tiếng Việt thật đẹp khi anh có thể gọi em là vợ iu",
    "Anh từng nghĩ cuộc sống thật nhạt nhẽo, cho đến khi em đến bên cạnh anh",
    "Cảm ơn em",
    "Yêuu em",
    "Anh yêu em",
    "I love you",
    "Anh yêu bé",
    "Tớ yêu cậu",
    "Yêuuuu em nhìuuu",
    "Thương bé nhất",
    "Chụt chụt chụt",
    "Moaaaaa",
    "Yêuu em nhắm",
    "Yêuu embe nhất",
    "Chồng yêu vợ nhìu",
    "Làm vợ anh nheee", 
    "Anh yêu em",
    "I love you",
    "Anh yêu bé",
    "Tớ yêu cậu",
    "Yêuuuu em nhìuuu",
    "Thương bé nhất",
    "Chụt chụt chụt",
    "Moaaaaa",
    "Yêuu em nhắm",
    "Yêuu embe nhất",
    "Chồng yêu vợ nhìu",
    "Làm vợ anh nheee", 
"Anh yêu em",
    "I love you",
    "Anh yêu bé",
    "Tớ yêu cậu",
    "Yêuuuu em nhìuuu",
    "Thương bé nhất",
    "Chụt chụt chụt",
    "Moaaaaa",
    "Yêuu em nhắm",
    "Yêuu embe nhất",
    "Chồng yêu vợ nhìu",
    "Làm vợ anh nheee", 
"Anh yêu em",
    "I love you",
    "Anh yêu bé",
    "Tớ yêu cậu",
    "Yêuuuu em nhìuuu",
    "Thương bé nhất",
    "Chụt chụt chụt",
    "Moaaaaa",
    "Yêuu em nhắm",
    "Yêuu embe nhất",
    "Chồng yêu vợ nhìu",
    "Làm vợ anh nheee", 
"Anh yêu em",
    "I love you",
    "Anh yêu bé",
    "Tớ yêu cậu",
    "Yêuuuu em nhìuuu",
    "Thương bé nhất",
    "Chụt chụt chụt",
    "Moaaaaa",
    "Yêuu em nhắm",
    "Yêuu embe nhất",
    "Chồng yêu vợ nhìu",
    "Làm vợ anh nheee" ,



];
document.getElementById("loop").addEventListener("click", (e) => {
    if (e.target.classList.contains("heart")) {
        let random_text = Math.floor(Math.random()*text_src.length);
        let top = window.getComputedStyle(e.target).top;
        e.target.classList.remove("heart");
        e.target.classList.add("heart_clicked");
        e.target.style.top = top;
        e.target.innerText= text_src[random_text];

    }
  });
  